### ISSUE TITLE
Manifest has incorrect implementation version

### ISSUE THREAD

**Issue by sschr15** [PatchworkMC/patchwork-patcher#87]
In a freshly built all-jar using the included gradle wrapper and on the latest commit as of creating this issue (f73eb9249c1ce4ef28cb0d2978aea20df3baf092), the generated manifest has a questionable value that appears Gradle has not correctly given. Below is the generated manifest:
```yaml
Manifest-Version: 1.0
Implementation-Title: Patchwork Patcher
Implementation-Version: task ':jar' property 'archiveVersion'
Main-Class: net.patchworkmc.patcher.ui.PatchworkUI
```

This apparent problem is in all three shadow jars, but it is not present in the jar not containing dependencies.
